export const timeAgoTranslations: Record<string, string> = {
  'years ago_pt_br': '{X} anos atrás',
  'year ago_pt_br': '{X} ano atrás',
  'months ago_pt_br': '{X} meses atrás',
  'month ago_pt_br': '{X} mês atrás',
  'days ago_pt_br': '{X} dias atrás',
  'day ago_pt_br': '{X} dia atrás',
  'hours ago_pt_br': '{X} horas atrás',
  'hour ago_pt_br': '{X} hora atrás',
  'minutes ago_pt_br': '{X} minutos atrás',
  'minute ago_pt_br': '{X} minuto atrás',
  'seconds ago_pt_br': '{X} segundos atrás',
  'second ago_pt_br': '{X} segundo atrás',
  'default_pt_br': 'Momentos atrás',

  'years left_pt_br': '{X} anos restantes',
  'year left_pt_br': '{X} ano restante',
  'months left_pt_br': '{X} meses restantes',
  'month left_pt_br': '{X} mês restante',
  'days left_pt_br': '{X} dias restantes',
  'day left_pt_br': '{X} dia restante',

  'years ago_es': 'Hace {X} años',
  'year ago_es': 'Hace {X} año',
  'months ago_es': 'Hace {X} meses',
  'month ago_es': 'Hace {X} mes',
  'days ago_es': 'Hace {X} días',
  'day ago_es': 'Hace {X} día',
  'hours ago_es': 'Hace {X} horas',
  'hour ago_es': 'Hace {X} hora',
  'minutes ago_es': 'Hace {X} minutos',
  'minute ago_es': 'Hace {X} minuto',
  'seconds ago_es': 'Hace {X} segundos',
  'second ago_es': 'Hace {X} segundo',
  'default_es': 'Hace momentos',

  'years left_es': 'Faltan {X} años',
  'year left_es': 'Falta {X} año',
  'months left_es': 'Faltan {X} meses',
  'month left_es': 'Falta {X} mes',
  'days left_es': 'Faltan {X} días',
  'day left_es': 'Falta {X} día',

  'years ago_ru': '{X} года назад',
  'year ago_ru': '{X} год назад',
  'months ago_ru': '{X} месяца назад',
  'month ago_ru': '{X} месяц назад',
  'days ago_ru': '{X} дня назад',
  'day ago_ru': '{X} день назад',
  'hours ago_ru': '{X} часа назад',
  'hour ago_ru': '{X} час назад',
  'minutes ago_ru': '{X} минуты назад',
  'minute ago_ru': '{X} минуту назад',
  'seconds ago_ru': '{X} секунд назад',
  'second ago_ru': '{X} секунду назад',
  'default_ru': 'Несколько минут назад',

  'years left_ru': 'осталось {X} лет',
  'year left_ru': 'Остался {X} год',
  'months left_ru': 'осталось {X} месяцев',
  'month left_ru': 'Остался {X} месяц',
  'days left_ru': 'осталось {X} дней',
  'day left_ru': 'Остался {X} день'
};

export const serverResponsesTranslations: Record<string, string> = {
  BAD_PASSWORD_3_pt_br: 'Senha fraca: Senha deve possuir pelo menos 8 letras, 1 maiúscula, 1 caracter especial',
  BAD_PASSWORD_2_pt_br: 'Senha fraca: Senha deve possuir pelo menos 1 maiúscula, 1 caracter especial',
  BAD_PASSWORD_1_pt_br: 'Senha fraca: Senha deve possuir pelo menos 1 caracter especial',
  EMAIL_EXISTS_pt_br: 'E-mail já cadastrado!',
  FORBIDDEN_pt_br: 'Proibido! Acesso negado',
  INTERNAL_ERROR_pt_br: 'Erro Interno do Servidor!',
  MAX_LOGIN_ATTEMPT_pt_br: 'Limite máximo de tentativas atingido. Por favor aguarde 30 minutos',
  FILL_ALL_FIELDS_pt_br: 'Por ravor, preencha todos os campos',
  FILL_USER_AND_PASS_pt_br: 'Por favor, informe seu e-mail e senha!',
  FILL_AT_LEAST_3_pt_br: 'Por favor, digite pelo menos 3 letras',
  MAX_TEXT_LENGTH_2000_pt_br: 'O tamanho máximo do texto é 2000',
  UNKNOWN_pt_br: 'Erro desconhecido',
  WRONG_OR_MISSING_INFO_pt_br: 'Informação errada ou incompleta!',
  WRONG_USER_OR_PASS_pt_br: 'E-mail ou senha inválidos!',

  BAD_PASSWORD_3_es: 'Contraseña inválida: La contraseña debe tener al menos 8 caracteres, 1 mayúscula y 1 carácter especial',
  BAD_PASSWORD_2_es: 'Contraseña inválida: La contraseña debe tener al menos 1 mayúscula y 1 carácter especial',
  BAD_PASSWORD_1_es: 'Contraseña inválida: La contraseña debe tener al menos 1 carácter especial',
  EMAIL_EXISTS_es: '¡El correo ya está registrado!',
  FORBIDDEN_es: '¡Prohibido! Acceso denegado',
  INTERNAL_ERROR_es: '¡Error interno del servidor!',
  MAX_LOGIN_ATTEMPT_es: 'Has alcanzado el límite máximo de intentos de inicio de sesión. Por favor, espera 30 minutos',
  FILL_ALL_FIELDS_es: 'Por favor, completa todos los campos',
  FILL_USER_AND_PASS_es: '¡Por favor, ingresa tu nombre de usuario y contraseña!',
  FILL_AT_LEAST_3_es: '¡Por favor, escriba al menos 3 caracteres!',
  MAX_TEXT_LENGTH_2000_es: 'La longitud máxima del texto es 2000',
  UNKNOWN_es: 'Error desconocido',
  WRONG_OR_MISSING_INFO_es: '¡Información incorrecta o incompleta!',
  WRONG_USER_OR_PASS_es: '¡Usuario o contraseña incorrectos!',

  BAD_PASSWORD_3_ru: 'Неправильный пароль: Пароль должен содержать не менее 8 символов, 1 заглавную букву, 1 специальный символ.',
  BAD_PASSWORD_2_ru: 'Неправильный пароль: Пароль должен содержать как минимум 1 заглавную букву и 1 специальный символ.',
  BAD_PASSWORD_1_ru: 'Неправильный пароль: Пароль должен содержать хотя бы 1 специальный символ.',
  EMAIL_EXISTS_ru: 'Электронная почта уже существует!',
  FORBIDDEN_ru: 'Запрещено! Доступ запрещен!',
  INTERNAL_ERROR_ru: 'Внутренняя ошибка сервера!',
  MAX_LOGIN_ATTEMPT_ru: 'Достигнут максимальный лимит попыток входа. Пожалуйста, подождите 30 минут',
  FILL_ALL_FIELDS_ru: 'Пожалуйста, заполните все поля',
  FILL_USER_AND_PASS_ru: 'Пожалуйста, введите свое имя пользователя и пароль!',
  FILL_AT_LEAST_3_ru: 'Пожалуйста, введите не менее 3 символов',
  MAX_TEXT_LENGTH_2000_ru: 'Максимальная длина текста — 2000.',
  UNKNOWN_ru: 'Неизвестная ошибка',
  WRONG_OR_MISSING_INFO_ru: 'Неверная или отсутствующая информация!',
  WRONG_USER_OR_PASS_ru: 'Неправильный пользователь или пароль'
};
