export const timeAgoTranslations: Record<string, string> = {
  'years ago_pt_br': '{X} anos atrás',
  'year ago_pt_br': '{X} ano atrás',
  'months ago_pt_br': '{X} meses atrás',
  'month ago_pt_br': '{X} mês atrás',
  'days ago_pt_br': '{X} dias atrás',
  'day ago_pt_br': '{X} dia atrás',
  'hours ago_pt_br': '{X} horas atrás',
  'hour ago_pt_br': '{X} hora atrás',
  'minutes ago_pt_br': '{X} minutos atrás',
  'minute ago_pt_br': '{X} minuto atrás',
  'seconds ago_pt_br': '{X} segundos atrás',
  'second ago_pt_br': '{X} segundo atrás',
  'default_pt_br': 'Momentos atrás',

  'years left_pt_br': '{X} anos restantes',
  'year left_pt_br': '{X} ano restante',
  'months left_pt_br': '{X} meses restantes',
  'month left_pt_br': '{X} mês restante',
  'days left_pt_br': '{X} dias restantes',
  'day left_pt_br': '{X} dia restante',

  'years ago_es': 'Hace {X} años',
  'year ago_es': 'Hace {X} año',
  'months ago_es': 'Hace {X} meses',
  'month ago_es': 'Hace {X} mes',
  'days ago_es': 'Hace {X} días',
  'day ago_es': 'Hace {X} día',
  'hours ago_es': 'Hace {X} horas',
  'hour ago_es': 'Hace {X} hora',
  'minutes ago_es': 'Hace {X} minutos',
  'minute ago_es': 'Hace {X} minuto',
  'seconds ago_es': 'Hace {X} segundos',
  'second ago_es': 'Hace {X} segundo',
  'default_es': 'Hace momentos',

  'years left_es': 'Faltan {X} años',
  'year left_es': 'Falta {X} año',
  'months left_es': 'Faltan {X} meses',
  'month left_es': 'Falta {X} mes',
  'days left_es': 'Faltan {X} días',
  'day left_es': 'Falta {X} día',

  'years ago_ru': '{X} года назад',
  'year ago_ru': '{X} год назад',
  'months ago_ru': '{X} месяца назад',
  'month ago_ru': '{X} месяц назад',
  'days ago_ru': '{X} дня назад',
  'day ago_ru': '{X} день назад',
  'hours ago_ru': '{X} часа назад',
  'hour ago_ru': '{X} час назад',
  'minutes ago_ru': '{X} минуты назад',
  'minute ago_ru': '{X} минуту назад',
  'seconds ago_ru': '{X} секунд назад',
  'second ago_ru': '{X} секунду назад',
  'default_ru': 'Несколько минут назад',

  'years left_ru': 'осталось {X} лет',
  'year left_ru': 'Остался {X} год',
  'months left_ru': 'осталось {X} месяцев',
  'month left_ru': 'Остался {X} месяц',
  'days left_ru': 'осталось {X} дней',
  'day left_ru': 'Остался {X} день'
};
