spring:
  application:
    name: tasknote-api

server:
  port: 8585
  error:
    include-message: always
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/server}

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    br.com.tasknoteapp.server: ${SERVER_API_LOG_LEVEL:INFO}

# Actuator and ops
management:
  endpoint:
    health:
      show-details: always

# Database, datasource and JPA
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5435}/${POSTGRES_DB:tasknote}
    username: ${POSTGRES_USER:tasknoteuser}
    password: ${POSTGRES_PASSWORD:default}
spring:
  jpa:
    properties:
      hibernate:
        default_schema: tasknote
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    jpa.show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Native Cloud
springdoc:
  enable-native-support: true

# Version (build)
br:
  com:
    tasknote:
      server:
        version: ${BUILD:local}
        allowed-cors-origins: ${CORS_ALLOWED_ORIGINS:http://localhost}
