name: CI

on:
  push:
    branches:
      - '*'
      - '*/*'

jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          node-version: '20'
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Clean and Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      #- name: Unit tests
      #  run: npm run test
