name: CI

on:
  push:
    branches:
      - '*'
      - '*/*'

jobs:
  client-code-checks:
    name: Client Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          node-version: '20'
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Clean and Install
        run: cd client && npm ci
      - name: Build
        run: cd client && npm run build
      - name: Lint
        run: cd client && npm run lint
      #- name: Unit tests
      #  run: npm run test

  java-code-checks:
    name: Java Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: cd java-api && ./mvnw --no-transfer-progress clean compile -DskipTests

      - name: Google Checkstyle
        run: cd java-api && ./mvnw --no-transfer-progress checkstyle:checkstyle -Dskip.checkstyle=false

      - name: All Tests
        run: cd java-api && ./mvnw --no-transfer-progress clean verify -P all-tests --file pom.xml