name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Set up Node
        with:
          node-version: '20'
      - name: Clean and Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      #- name: Unit tests
      #  run: npm run test

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs:
      - code-checks
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rmcampos/tasknote:${{ github.event.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
